### ISSUE TITLE
Compiled version

### ISSUE THREAD

**Issue by Cianez** [wildex999/GameCouchOnline#1]
Could you please provide a compiled version of your tool? Many of us are not programmers but we'd like to test your GameCouchOnline and provide feedback.

Thank you in advance.

**Comment by wildex999** [comment]
Hello.
Sorry, but there will probably never be a compiled version. This is just an experiment I did some time ago, and is probably only of use as a learning resource for programmers who would like to create something similar.

**Comment by Cianez** [comment]
> 
> 
> Hello.
> Sorry, but there will probably never be a compiled version. This is just an experiment I did some time ago, and is probably only of use as a learning resource for programmers who would like to create something similar.

Hi.
I see. I'm sorry to hear that. It seems like a nice little tool that shouldn't be leaved there unfinished in my opinion.

Have a good day!

**Comment by wildex999** [comment]
Maybe ;)
But in the end there already exists multiple tools which does this:
- Parsec Gaming (PC Tools which pretty much does what GameCouchOnline would have done).
- Steam In-Home Streaming & Stream to another computer. Works fantastic with low ping(Same city on fiber etc.)
- GeForce Shadowplay (Used by the NVidia Shield, but can also stream between computer with Nvidia cards)
And others.

**Comment by Cianez** [comment]
The main problem about Parsec is that you can't host on Windows 7 (just being a client works, and I have Windows 7).
Shadowplay has pretty high requirements; I own an ASUS GTX 770 DirectCU II OC and it's not compatible with GameStream. If you want to play old games, or games that runs on ePSXe, with people that have old computers you simply can't (that for Parsec too).
Steam In-Home Streaming needs to have all the players logged in the same account; hence if you want to play with someone you'd have to make them access your Steam account (which is not really recommended).

These are the main reasons why me and my friends are interested in your tool. :smiley:
